//
//  PHInitialRequest.swift
//  payHereSDK
//
//  Created by Kamal Upasena on 1/23/20.
//  Copyright © 2020 PayHere. All rights reserved.
//

import Foundation

public class PHInitialRequest{
    
    internal var merchantID, notifyURL: String?
    internal var firstName, lastName, email, phone: String?
    internal var address, city, country, orderID: String?
    internal var itemsDescription: String?
    internal var itemsMap: [Item]?
    internal var currency : PHCurrency?
    internal var amount : Double?
    internal var deliveryAddress, deliveryCity, deliveryCountry: String?
    internal var custom1, custom2 : String?
    
    internal var startupFee: Double?
    internal var recurrence : PHRecurrenceTime?
    internal var duration: PHDuration?
    internal var api : SelectedAPI = .CheckOut
    internal var isHoldOnCardEnabled : Bool = false
    
    /**
     Use this constructor when you are using [PayHere Checkout API](https://support.payhere.lk/api-&-mobile-sdk/payhere-checkout)
     - Parameter merchantID: Merchant ID Obtain From PayHere.
     - Parameter notifyURL: URL to callback the status of the payment (Needs to be a URL accessible on a public IP/domain)
     - Parameter firstName: First Name of the Customer.
     - Parameter lastName: Last Name of the Customer.
     - Parameter email : Customer’s Email
     - Parameter phone : Customer’s Phone No
     - Parameter address : Customer’s Address Line1 + Line2
     - Parameter city : Customer’s City
     - Parameter country : Customer’s Country
     - Parameter orderID : Order ID generated by the merchant
     - Parameter items : List of `Item`
     - Parameter currency : `PHCurrency` Object
     - Parameter amount : Total Payment Amount
     - Parameter deliveryAddress : Delivery Address Line1 + Line2 (Optional)
     - Parameter deliveryCity : Delivery City (Optinal)
     - Parameter deliveryCountry : Delivery Country (Optional)
     - Parameter custom1 : Custom param 1 set by merchant (Optional)
     - Parameter custom2 : Custom param 2 set by merchant (Optional)
     */
    public init(merchantID: String?, notifyURL: String?, firstName: String?, lastName: String?, email: String?, phone: String?, address: String?, city: String?, country: String?, orderID: String?, itemsDescription: String?, itemsMap: [Item]?, currency: PHCurrency?, amount: Double?, deliveryAddress: String?, deliveryCity: String?, deliveryCountry: String?, custom1: String?, custom2: String?) {
        self.merchantID = merchantID
        self.notifyURL = notifyURL
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phone = phone
        self.address = address
        self.city = city
        self.country = country
        self.orderID = orderID
        self.itemsDescription = itemsDescription
        self.itemsMap = itemsMap
        self.currency = currency
        self.amount = amount
        self.deliveryAddress = deliveryAddress
        self.deliveryCity = deliveryCity
        self.deliveryCountry = deliveryCountry
        self.custom1 = custom1
        self.custom2 = custom2
        self.api = .CheckOut
    }
    
    /**
    Use this constructor when you are using [PayHere Recurring API](https://support.payhere.lk/api-&-mobile-sdk/payhere-recurring)
    - Parameter merchantID: Merchant ID Obtain From PayHere.
    - Parameter notifyURL: URL to callback the status of the payment (Needs to be a URL accessible on a public IP/domain)
    - Parameter firstName: First Name of the Customer.
    - Parameter lastName: Last Name of the Customer.
    - Parameter email : Customer’s Email
    - Parameter phone : Customer’s Phone No
    - Parameter address : Customer’s Address Line1 + Line2
    - Parameter city : Customer’s City
    - Parameter country : Customer’s Country
    - Parameter order_id : Order ID generated by the merchant
    - Parameter items : List of `Item`
    - Parameter currency : `PHCurrency`
    - Parameter amount : Total Payment Amount
    - Parameter recurrence : `PHRecurrenceTime`
    - Parameter duration : `PHDuration`
    - Parameter deliveryAddress : Delivery Address Line1 + Line2 (Optional)
    - Parameter deliveryCity : Delivery City (Optinal)
    - Parameter deliveryCountry : Delivery Country (Optional)
    - Parameter custom1 : Custom param 1 set by merchant (Optional)
    - Parameter custom2 : Custom param 2 set by merchant (Optional)
   
    */
    
    public  init(merchantID: String?, notifyURL: String?, firstName: String?, lastName: String?, email: String?, phone: String?, address: String?, city: String?, country: String?, orderID: String?, itemsDescription: String?, itemsMap: [Item]?, currency: PHCurrency?, amount: Double?, deliveryAddress: String?, deliveryCity: String?, deliveryCountry: String?, custom1: String?, custom2: String?, startupFee: Double?, recurrence: PHRecurrenceTime?, duration: PHDuration?) {
        self.merchantID = merchantID
        self.notifyURL = notifyURL
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phone = phone
        self.address = address
        self.city = city
        self.country = country
        self.orderID = orderID
        self.itemsDescription = itemsDescription
        self.itemsMap = itemsMap
        self.currency = currency
        self.amount = amount
        self.deliveryAddress = deliveryAddress
        self.deliveryCity = deliveryCity
        self.deliveryCountry = deliveryCountry
        self.custom1 = custom1
        self.custom2 = custom2
       
        
        self.startupFee = startupFee
        self.recurrence = recurrence
        self.duration = duration
        self.api = .Recurrence
    }
    
    /**
     Use this constructor when you are using [PayHere Preapproval API](https://support.payhere.lk/api-&-mobile-sdk/payhere-preapproval)
     - Parameter merchantID: Merchant ID Obtain From PayHere.
     - Parameter notifyURL: URL to callback the status of the payment (Needs to be a URL accessible on a public IP/domain)
     - Parameter firstName: First Name of the Customer.
     - Parameter lastName: Last Name of the Customer.
     - Parameter email : Customer’s Email
     - Parameter phone : Customer’s Phone No
     - Parameter address : Customer’s Address Line1 + Line2
     - Parameter city : Customer’s City
     - Parameter country : Customer’s Country
     - Parameter orderID : Order ID generated by the merchant
     - Parameter items : List of `Item`
     - Parameter currency : `PHCurrency` Object
     - Parameter custom1 : Custom param 1 set by merchant (Optional)
     - Parameter custom2 : Custom param 2 set by merchant (Optional)
     - Parameter amount : PreApproval Initial Charge Amount (Optional)
     */
    
    public init(merchantID: String?, notifyURL: String?, firstName: String?, lastName: String?, email: String?, phone: String?, address: String?, city: String?, country: String?, orderID: String?, itemsDescription: String?, itemsMap: [Item]?, currency: PHCurrency?, custom1: String? = nil, custom2: String? = nil,amount: Double = 0.0) {
        self.merchantID = merchantID
        self.notifyURL = notifyURL
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phone = phone
        self.address = address
        self.city = city
        self.country = country
        self.orderID = orderID
        self.itemsDescription = itemsDescription
        self.itemsMap = itemsMap
        self.currency = currency
        self.custom1 = custom1
        self.custom2 = custom2
        if amount > 0.0{
            self.amount  = amount
        }
        self.api =  .PreApproval
    }
    
    /**
     Use this constructor when you are using [PayHere Authorize API](https://support.payhere.lk/api-&-mobile-sdk/payhere-authorize)
     - Parameter merchantID: Merchant ID Obtain From PayHere.
     - Parameter notifyURL: URL to callback the status of the payment (Needs to be a URL accessible on a public IP/domain)
     - Parameter firstName: First Name of the Customer.
     - Parameter lastName: Last Name of the Customer.
     - Parameter email : Customer’s Email
     - Parameter phone : Customer’s Phone No
     - Parameter address : Customer’s Address Line1 + Line2
     - Parameter city : Customer’s City
     - Parameter country : Customer’s Country
     - Parameter orderID : Order ID generated by the merchant
     - Parameter items : List of `Item`
     - Parameter currency : `PHCurrency` Object
     - Parameter amount : Total Payment Amount
     - Parameter custom1 : Custom param 1 set by merchant (Optional)
     - Parameter custom2 : Custom param 2 set by merchant (Optional)
     */
    public init(merchantID: String?, notifyURL: String?, firstName: String?, lastName: String?, email: String?, phone: String?, address: String?, city: String?, country: String?, orderID: String?, itemsDescription: String?, itemsMap: [Item]?, currency: PHCurrency?, amount: Double?, deliveryAddress: String?, deliveryCity: String?, deliveryCountry: String?, custom1: String?, custom2: String?,isHoldOnCardEnabled : Bool) {
        self.merchantID = merchantID
        self.notifyURL = notifyURL
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.phone = phone
        self.address = address
        self.city = city
        self.country = country
        self.orderID = orderID
        self.itemsDescription = itemsDescription
        self.itemsMap = itemsMap
        self.currency = currency
        self.amount = amount
        self.custom1 = custom1
        self.custom2 = custom2
        self.isHoldOnCardEnabled = isHoldOnCardEnabled
        self.api = .Authorize
    }
    
    
    
    
    
}
